# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-Ngf9Te_tPdJXzYSnK8xETNjEcW-iwM
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,f1_score,precision_score,recall_score
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

path="/content/sed.csv"
df = pd.read_csv(path)
df.head(50)

df.info()
# getting the characteristic information of the dataset

df.isnull().sum()
#  Checking the null values of the dataset

X = df.iloc[:,1:3001]
y = df.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state=5)

rfc = RandomForestClassifier(random_state=4)

rfc.fit(X_train,y_train)


print("Test Results \n")
y_test_pred  = rfc.predict(X_test)
y_test_prob = rfc.predict_proba(X_test)[:,1]

print("Confusion Matrix for Test : \n", confusion_matrix(y_test, y_test_pred))
print("Accuracy Score for Test : ", accuracy_score(y_test, y_test_pred))
print("f1 score for Random Forst : ", f1_score(y_test,y_test_pred))
print("Precision score for Random Forst : ", precision_score(y_test,y_test_pred))
print("Recall score for Random Forst : ", recall_score(y_test,y_test_pred))